apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: spring-boot-cd
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service.spring-cd.svc.cluster.local:5432/mydb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "myuser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123"
